/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as EstudosRouteImport } from './routes/estudos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as AuthResetRouteImport } from './routes/auth.reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosRoute = EstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/estudos': typeof EstudosRoute
  '/financeiro': typeof FinanceiroRoute
  '/hobbies': typeof HobbiesRoute
  '/mercado': typeof MercadoRoute
  '/tarefas': typeof TarefasRoute
  '/treino': typeof TreinoRoute
  '/auth/reset': typeof AuthResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/estudos': typeof EstudosRoute
  '/financeiro': typeof FinanceiroRoute
  '/hobbies': typeof HobbiesRoute
  '/mercado': typeof MercadoRoute
  '/tarefas': typeof TarefasRoute
  '/treino': typeof TreinoRoute
  '/auth/reset': typeof AuthResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/estudos': typeof EstudosRoute
  '/financeiro': typeof FinanceiroRoute
  '/hobbies': typeof HobbiesRoute
  '/mercado': typeof MercadoRoute
  '/tarefas': typeof TarefasRoute
  '/treino': typeof TreinoRoute
  '/auth/reset': typeof AuthResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dieta'
    | '/estudos'
    | '/financeiro'
    | '/hobbies'
    | '/mercado'
    | '/tarefas'
    | '/treino'
    | '/auth/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dieta'
    | '/estudos'
    | '/financeiro'
    | '/hobbies'
    | '/mercado'
    | '/tarefas'
    | '/treino'
    | '/auth/reset'
  id:
    | '__root__'
    | '/'
    | '/dieta'
    | '/estudos'
    | '/financeiro'
    | '/hobbies'
    | '/mercado'
    | '/tarefas'
    | '/treino'
    | '/auth/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DietaRoute: typeof DietaRoute
  EstudosRoute: typeof EstudosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HobbiesRoute: typeof HobbiesRoute
  MercadoRoute: typeof MercadoRoute
  TarefasRoute: typeof TarefasRoute
  TreinoRoute: typeof TreinoRoute
  AuthResetRoute: typeof AuthResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos': {
      id: '/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof EstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DietaRoute: DietaRoute,
  EstudosRoute: EstudosRoute,
  FinanceiroRoute: FinanceiroRoute,
  HobbiesRoute: HobbiesRoute,
  MercadoRoute: MercadoRoute,
  TarefasRoute: TarefasRoute,
  TreinoRoute: TreinoRoute,
  AuthResetRoute: AuthResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
